### PR TITLE
Disable all optional stuff present in freetype

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/libfreetype2/23)

### CODE REVIEW

**Comment by emilio** [comment]
Have you confirmed that we don't use any of this stuff? r=me with that

**Comment by nox** [comment]
@emilio It wasn't enabled before when we were not relying on upstream's CMake, AFAICT.

**Comment by larsbergstrom** [comment]
Passed: https://travis-ci.org/servo/libfreetype2/builds/150978665

**Pull request merged**
